### ISSUE TITLE
Error when inviting an user to join an app by email 

### ISSUE THREAD

**Issue by bobeal** [ozwillo/ozwillo-kernel#7]
Hello,

I'm currently working on the [possibility to invite an app_user outside the admin organization](https://github.com/ozwillo/ozwillo-portal/issues/207) but I get an error when I try to invite an user by its email.

Here are the logs of the call to the kernel : 

```
| WARN | 19:27:12.473 | org.oasis_eu.spring.util.KernelLoggingInterceptor - POST request to https://kernel.ozwillo-dev.eu/apps/acl/instance/3e4ca7cd-8837-4675-93e7-839a7361edb8 resulted in 500 Internal Server Error
| INFO | 19:27:12.474 | org.oasis_eu.spring.util.KernelLoggingInterceptor - Request body: {"instance_id":"3e4ca7cd-8837-4675-93e7-839a7361edb8","email":"mon@email.com","app_admin":false,"app_user":true}
```

And here is what I saw in the kernel logs : 

```
2016-02-03 19:27:12,824 ERROR o.w.a.AppInstanceAccessControlEndpoint [pool-5-thread-3984] Error notifying a user about an invitation for using an app-instance
com.google.template.soy.data.SoyDataException: Attempting to convert unrecognized object to Soy data (object type oasis.model.i18n.LocalizableString).
	at com.google.template.soy.data.SoyData.createFromExistingData(SoyData.java:110) ~[soy-2015-04-10.jar:?]
	at com.google.template.soy.data.restricted.CollectionData.put(CollectionData.java:57) ~[soy-2015-04-10.jar:?]
	at oasis.web.applications.AppInstanceAccessControlEndpoint.notifyUserForNewAppInstanceInvitation(AppInstanceAccessControlEndpoint.java:250) ~[oasis-webapp-1.40.0-0-g9b8ee1e.jar:?]
	at oasis.web.applications.AppInstanceAccessControlEndpoint.addToList(AppInstanceAccessControlEndpoint.java:220) [oasis-webapp-1.40.0-0-g9b8ee1e.jar:?]
```

**Comment by tbroyer** [comment]
Should be fixed in 72cd8459d0d27f1365e5361ccdbc79f67b65b794
Will be live on ozwillo-dev tomorrow morning.
Thanks for the report.
